/**
 * Sistema de Permisos - LGS Admin Panel
 * Tipos y definiciones para el control de acceso basado en roles
 */

// ============================================================================
// TIPOS BASE
// ============================================================================

/**
 * Módulos principales de la aplicación
 */
export enum Module {
  PERSON = 'PERSON',
  STUDENT = 'STUDENT',
  ACADEMICO = 'ACADEMICO',
  INFORMES = 'INFORMES',
  SERVICIO = 'SERVICIO',
  COMERCIAL = 'COMERCIAL',
  APROBACION = 'APROBACION',
  MANTENIMIENTO = 'MANTENIMIENTO',
  RECAUDOS = 'RECAUDOS',
}

/**
 * Roles disponibles en el sistema
 */
export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  ADVISOR = 'ADVISOR',
  COMERCIAL = 'COMERCIAL',
  APROBADOR = 'APROBADOR',
  APROBACION_GESTOR = 'APROBACION_GESTOR',
  APROBACION_CONTRATOS = 'APROBACION_CONTRATOS',
  TALERO = 'TALERO',
  FINANCIERO = 'FINANCIERO',
  SERVICIO = 'SERVICIO',
  SERVICIO_ASIST = 'SERVICIO_ASIST',
  SERVICIO_JEFE = 'SERVICIO_JEFE',
  RECAUDOS_ASIST = 'RECAUDO_ASIST',
  RECAUDOS_JEFE = 'RECAUDOS_JEFE',
  READONLY = 'READONLY',
  COORDINADOR_ACADEMICO = 'COORDINADOR_ACADEMICO',
  ACADEMICO_JEFE = 'ACADEMICO_JEFE',
  ADMINISTRACION_JEFE = 'ADMINISTRACION_JEFE',
  ESTUDIANTE = 'ESTUDIANTE',
}

// ============================================================================
// PERMISOS POR MÓDULO
// ============================================================================

/**
 * Permisos del módulo PERSON (Endpoint /person/)
 */
export enum PersonPermission {
  DESCARGAR_CONTRATO = 'PERSON.INFO.DESCARGAR_CONTRATO',
  VER_CONTRATO = 'PERSON.INFO.VER_CONTRATO',
  VER_DOCUMENTACION = 'PERSON.INFO.VER_DOCUMENTACION',
  ADICION_DOCUMENTACION = 'PERSON.INFO.ADICION_DOCUMENTACION',
  CAMBIO_CELULAR = 'PERSON.INFO.CAMBIO_CELULAR',
  CAMBIAR_ESTADO = 'PERSON.INFO.CAMBIAR_ESTADO',
  MODIFICAR = 'PERSON.INFO.MODIFICAR',
  AGREGAR_BENEFICIARIO = 'PERSON.INFO.AGREGAR_BENEFICIARIO',
  WHATSAPP = 'PERSON.INFO.WHATSAPP',
  ELIMINAR = 'PERSON.INFO.ELIMINAR',
  ASIGNAR_GESTOR_RECAUDO = 'PERSON.FINANCIERA.ASIGNAR_GESTOR_RECAUDO',
  CAMBIO_ESTADO_CARTERA  = 'PERSON.FINANCIERA.CAMBIO_ESTADO_CARTERA',
  MARCAR_OPCIONAL        = 'PERSON.FINANCIERA.MARCAR_OPCIONAL',
  PAGOS_VER              = 'PERSON.FINANCIERA.PAGOS_VER',
  PAGOS_REGISTRAR        = 'PERSON.FINANCIERA.PAGOS_REGISTRAR',
  PAGOS_VALIDAR          = 'PERSON.FINANCIERA.PAGOS_VALIDAR',
  PAGOS_ELIMINAR         = 'PERSON.FINANCIERA.PAGOS_ELIMINAR',
  PAGOS_RECIBO           = 'PERSON.FINANCIERA.PAGOS_RECIBO',

  // Legacy permissions (keeping for backward compatibility)
  ACTIVAR_DESACTIVAR = 'PERSON.ADMIN.ACTIVAR_DESACTIVAR',
  APROBAR = 'PERSON.ADMIN.APROBAR',
}

/**
 * Permisos del módulo STUDENT (Endpoint /student/[id])
 */
export enum StudentPermission {
  // Globales
  ENVIAR_MENSAJE = 'STUDENT.GLOBAL.ENVIAR_MENSAJE',
  GUARDAR_PLANTILLA = 'STUDENT.GLOBAL.GUARDAR_PLANTILLA',
  CONSULTA_CONTRATO = 'STUDENT.GLOBAL.CONSULTA_CONTRATO',
  GENERAR_ESTADO_CUENTA = 'STUDENT.GLOBAL.GENERAR_ESTADO_CUENTA',

  // Academia
  TABLA_FILTROS = 'STUDENT.ACADEMIA.TABLA_FILTROS',
  TABLA_DESCARGAR = 'STUDENT.ACADEMIA.TABLA_DESCARGAR',
  COMO_VOY = 'STUDENT.ACADEMIA.COMO_VOY',
  EVALUACION = 'STUDENT.ACADEMIA.EVALUACION',
  ANOTACION_ADVISOR = 'STUDENT.ACADEMIA.ANOTACION_ADVISOR',
  COMENTARIOS_ESTUDIANTE = 'STUDENT.ACADEMIA.COMENTARIOS_ESTUDIANTE',
  ELIMINAR_EVENTO = 'STUDENT.ACADEMIA.ELIMINAR_EVENTO',
  AGENDAR_CLASE = 'STUDENT.ACADEMIA.AGENDAR_CLASE',
  MARCAR_STEP = 'STUDENT.ACADEMIA.MARCAR_STEP',
  ASIGNAR_STEP = 'STUDENT.ACADEMIA.ASIGNAR_STEP',
  INICIALIZAR_NIVEL = 'STUDENT.ACADEMIA.INICIALIZAR_NIVEL',

  // Contrato
  CONSULTA = 'STUDENT.CONTRATO.CONSULTA',
  ACTIVAR_HOLD = 'STUDENT.CONTRATO.ACTIVAR_HOLD',
  EXTENDER_VIGENCIA = 'STUDENT.CONTRATO.EXTENDER_VIGENCIA',

  // Financiera
  GENERAR_ESTADO = 'STUDENT.FINANCIERA.GENERAR_ESTADO',
  REGISTRAR_PAGO = 'STUDENT.FINANCIERA.REGISTRAR_PAGO',
  ENVIO_RECORDATORIO = 'STUDENT.FINANCIERA.ENVIO_RECORDATORIO',
}

/**
 * Permisos del módulo ACADEMICO (Menú Académico)
 */
export enum AcademicoPermission {
  // Agenda Sesiones
  VER_CALENDARIO = 'ACADEMICO.AGENDA.VER_CALENDARIO',
  VER_AGENDA = 'ACADEMICO.AGENDA.VER_AGENDA',
  CALENDARIO_VER = 'ACADEMICO.AGENDA.CALENDARIO_VER',
  LISTA_VER = 'ACADEMICO.AGENDA.LISTA_VER',
  FILTRO = 'ACADEMICO.AGENDA.FILTRO',
  NUEVO_EVENTO = 'ACADEMICO.AGENDA.NUEVO_EVENTO',
  EXPORTAR_CSV = 'ACADEMICO.AGENDA.EXPORTAR_CSV',
  EDITAR = 'ACADEMICO.AGENDA.EDITAR',
  ELIMINAR = 'ACADEMICO.AGENDA.ELIMINAR',
  CREAR_EVENTO = 'ACADEMICO.AGENDA.CREAR_EVENTO',
  VER_AGENDA_ACADEMICA = 'ACADEMICO.AGENDA.VER_AGENDA_ACADEMICA',
  IR_A_SESION = 'ACADEMICO.SESION.IR_A_SESION',

  // Agenda Académica
  VER = 'ACADEMICO.ACADEMICA.VER',
  AGENDAMIENTO = 'ACADEMICO.ACADEMICA.AGENDAMIENTO',
  ACADEMICA_EXPORTAR_CSV = 'ACADEMICO.ACADEMICA.EXPORTAR_CSV',
  ESTADISTICAS = 'ACADEMICO.ACADEMICA.ESTADISTICAS',
  EXPORTAR_STATS_CSV = 'ACADEMICO.ACADEMICA.EXPORTAR_STATS_CSV',

  // Advisor
  LISTA_ADVISORS_VER = 'ACADEMICO.ADVISOR.LISTA_VER',
  ADVISOR_VER_ENLACE = 'ACADEMICO.ADVISOR.VER_ENLACE',
  AGREGAR = 'ACADEMICO.ADVISOR.AGREGAR',
  ESTADISTICA = 'ACADEMICO.ADVISOR.ESTADISTICA',

  // Material
  ACTUALIZAR_MATERIAL = 'ACADEMICO.MATERIAL.ACTUALIZAR',

  // Control Horas
  CONTROL_HORAS_VER = 'ACADEMICO.CONTROL_HORAS.VER',
  // Permite seleccionar/cambiar de advisor en Ctrl Horas (ver el de otros,
  // no sólo el propio). SUPER_ADMIN/ADMIN lo tienen implícito.
  CONTROL_HORAS_VER_TODOS = 'ACADEMICO.CONTROL_HORAS.VER_TODOS',

  // Evaluaciones Jump (Bot Tutor) — revisar/aprobar reportes del bot
  JUMP_EVAL_REVISAR = 'ACADEMICO.JUMP_EVAL.REVISAR',

  // Performance Evaluation — dashboard de evaluaciones de estudiantes a advisors
  PERFORMANCE_EVAL_VER       = 'ACADEMICO.PERFORMANCE_EVAL.VER',
  PERFORMANCE_EVAL_EXPORTAR  = 'ACADEMICO.PERFORMANCE_EVAL.EXPORTAR',

  // Sesiones sin gestión — backlog de eventos pasados sin cerrar
  SESIONES_SIN_GESTION_VER   = 'ACADEMICO.SESIONES_SIN_GESTION.VER',
}

/**
 * Permisos del módulo INFORMES (Menú Informes)
 */
export enum InformesPermission {
  // Acceso general al módulo
  VER = 'INFORMES.VER',
  BENEFICIARIOS = 'INFORMES.BENEFICIARIOS',
  EXPORTAR = 'INFORMES.EXPORTAR',

  // Grupos individuales
  ASISTENCIA = 'INFORMES.ASISTENCIA',
  PROGRAMACION = 'INFORMES.PROGRAMACION',
  ADVISORS = 'INFORMES.ADVISORS',
  ACADEMICA = 'INFORMES.ACADEMICA',
  USUARIOS = 'INFORMES.USUARIOS',
  CONTRATOS = 'INFORMES.CONTRATOS',
  PLANTA = 'INFORMES.PLANTA',
  ESTADISTICAS = 'INFORMES.ESTADISTICAS',

  // Exportar / imprimir por grupo
  ASISTENCIA_EXPORTAR    = 'INFORMES.ASISTENCIA.EXPORTAR',
  PROGRAMACION_EXPORTAR  = 'INFORMES.PROGRAMACION.EXPORTAR',
  ADVISORS_EXPORTAR      = 'INFORMES.ADVISORS.EXPORTAR',
  USUARIOS_EXPORTAR      = 'INFORMES.USUARIOS.EXPORTAR',
  USUARIOS_IMPRIMIR      = 'INFORMES.USUARIOS.IMPRIMIR',
  CONTRATOS_EXPORTAR     = 'INFORMES.CONTRATOS.EXPORTAR',
  PLANTA_EXPORTAR        = 'INFORMES.PLANTA.EXPORTAR',
  ESTADISTICAS_EXPORTAR  = 'INFORMES.ESTADISTICAS.EXPORTAR',

  // ── Nivel 3 (nietos) — un permiso por reporte individual ──────────────
  // Asistencia
  ASIS_SESIONES          = 'INFORMES.ASISTENCIA.SESIONES',
  ASIS_CLUBES            = 'INFORMES.ASISTENCIA.CLUBES',
  ASIS_COMPLEMENTARIAS   = 'INFORMES.ASISTENCIA.COMPLEMENTARIAS',
  ASIS_WELCOME           = 'INFORMES.ASISTENCIA.WELCOME',
  ASIS_XPAIS             = 'INFORMES.ASISTENCIA.XPAIS',
  // Programación
  PROG_SESIONES_JUMPS    = 'INFORMES.PROGRAMACION.SESIONES_JUMPS',
  PROG_TRAINING_CLUBS    = 'INFORMES.PROGRAMACION.TRAINING_CLUBS',
  PROG_WELCOME           = 'INFORMES.PROGRAMACION.WELCOME',
  // Académica
  ACAD_HORAS_ADVISOR     = 'INFORMES.ACADEMICA.HORAS_ADVISOR',
  ACAD_INFOACADEMIC      = 'INFORMES.ACADEMICA.INFOACADEMIC',
  ACAD_HOLD_VIGENCIAS    = 'INFORMES.ACADEMICA.HOLD_VIGENCIAS',
  ACAD_X_NIVELES         = 'INFORMES.ACADEMICA.X_NIVELES',
  ACAD_CONCILIACION_STEPS = 'INFORMES.ACADEMICA.CONCILIACION_STEPS',
  ACAD_POR_VENCER        = 'INFORMES.ACADEMICA.POR_VENCER',
  // Contratos
  CONTRATOS_MATRICULAS     = 'INFORMES.CONTRATOS.MATRICULAS',
  CONTRATOS_MATRICULAS_EXP = 'INFORMES.CONTRATOS.MATRICULAS.EXPORTAR',
  CONTRATOS_MATRICULAS_PDF = 'INFORMES.CONTRATOS.MATRICULAS.IMPRIMIR',
  // Advisors
  ADV_SESIONES           = 'INFORMES.ADVISORS.SESIONES',
  ADV_JUMPS              = 'INFORMES.ADVISORS.JUMPS',
  ADV_TRAINING           = 'INFORMES.ADVISORS.TRAINING',
  ADV_CLUBES             = 'INFORMES.ADVISORS.CLUBES',
  ADV_WELCOME            = 'INFORMES.ADVISORS.WELCOME',
  ADV_ESSENTIAL          = 'INFORMES.ADVISORS.ESSENTIAL',
  ADV_RESUMEN            = 'INFORMES.ADVISORS.RESUMEN',
  // Planta
  PLANTA_ADVISORS        = 'INFORMES.PLANTA.ADVISORS',
  PLANTA_ADMINISTRATIVOS = 'INFORMES.PLANTA.ADMINISTRATIVOS',
  // Estadísticas
  EST_NIVELES            = 'INFORMES.ESTADISTICAS.NIVELES',
  EST_HORARIOS           = 'INFORMES.ESTADISTICAS.HORARIOS',

  // ── Botones por informe (Descargar CSV / Generar PDF) ─────────────────
  // Un permiso de export por reporte, listado debajo del informe en la matriz.
  // Los filtros NO llevan permiso (implícitos al autorizar el informe).
  ASIS_SESIONES_EXP        = 'INFORMES.ASISTENCIA.SESIONES.EXPORTAR',
  ASIS_CLUBES_EXP          = 'INFORMES.ASISTENCIA.CLUBES.EXPORTAR',
  ASIS_COMPLEMENTARIAS_EXP = 'INFORMES.ASISTENCIA.COMPLEMENTARIAS.EXPORTAR',
  ASIS_WELCOME_EXP         = 'INFORMES.ASISTENCIA.WELCOME.EXPORTAR',
  ASIS_XPAIS_EXP           = 'INFORMES.ASISTENCIA.XPAIS.EXPORTAR',
  PROG_SESIONES_JUMPS_EXP  = 'INFORMES.PROGRAMACION.SESIONES_JUMPS.EXPORTAR',
  PROG_TRAINING_CLUBS_EXP  = 'INFORMES.PROGRAMACION.TRAINING_CLUBS.EXPORTAR',
  PROG_WELCOME_EXP         = 'INFORMES.PROGRAMACION.WELCOME.EXPORTAR',
  ADV_SESIONES_EXP         = 'INFORMES.ADVISORS.SESIONES.EXPORTAR',
  ADV_JUMPS_EXP            = 'INFORMES.ADVISORS.JUMPS.EXPORTAR',
  ADV_TRAINING_EXP         = 'INFORMES.ADVISORS.TRAINING.EXPORTAR',
  ADV_CLUBES_EXP           = 'INFORMES.ADVISORS.CLUBES.EXPORTAR',
  ADV_WELCOME_EXP          = 'INFORMES.ADVISORS.WELCOME.EXPORTAR',
  ADV_ESSENTIAL_EXP        = 'INFORMES.ADVISORS.ESSENTIAL.EXPORTAR',
  ADV_RESUMEN_EXP          = 'INFORMES.ADVISORS.RESUMEN.EXPORTAR',
  ACAD_HORAS_ADVISOR_EXP   = 'INFORMES.ACADEMICA.HORAS_ADVISOR.EXPORTAR',
  ACAD_USUARIOS_EXP        = 'INFORMES.ACADEMICA.USUARIOS.EXPORTAR',
  ACAD_INFOACADEMIC_EXP    = 'INFORMES.ACADEMICA.INFOACADEMIC.EXPORTAR',
  ACAD_INFOACADEMIC_PDF    = 'INFORMES.ACADEMICA.INFOACADEMIC.IMPRIMIR',
  ACAD_HOLD_VIGENCIAS_EXP  = 'INFORMES.ACADEMICA.HOLD_VIGENCIAS.EXPORTAR',
  ACAD_X_NIVELES_EXP       = 'INFORMES.ACADEMICA.X_NIVELES.EXPORTAR',
  ACAD_CONCILIACION_STEPS_EXP = 'INFORMES.ACADEMICA.CONCILIACION_STEPS.EXPORTAR',
  ACAD_POR_VENCER_EXP      = 'INFORMES.ACADEMICA.POR_VENCER.EXPORTAR',
  EST_NIVELES_EXP          = 'INFORMES.ESTADISTICAS.NIVELES.EXPORTAR',
  EST_HORARIOS_EXP         = 'INFORMES.ESTADISTICAS.HORARIOS.EXPORTAR',
}

/**
 * Permisos del módulo SERVICIO (Menú Servicio)
 */
export enum ServicioPermission {
  // Welcome Session
  WELCOME_CARGAR_EVENTOS = 'SERVICIO.WELCOME.CARGAR_EVENTOS',
  WELCOME_EXPORTAR_CSV = 'SERVICIO.WELCOME.EXPORTAR_CSV',

  // Lista de Sesiones
  SESIONES_CARGAR_EVENTOS = 'SERVICIO.SESIONES.CARGAR_EVENTOS',
  SESIONES_EXPORTAR_CSV = 'SERVICIO.SESIONES.EXPORTAR_CSV',

  // Usuarios sin perfil
  USUARIOS_ACTUALIZAR = 'SERVICIO.USUARIOS.ACTUALIZAR',
  USUARIOS_EXPORTAR_CSV = 'SERVICIO.USUARIOS.EXPORTAR_CSV',

  // Exam. Intern. (IELTS / B2 First / TOEFL)
  EXAM_INTERN_IELTS_VER                  = 'SERVICIO.EXAM_INTERN.IELTS_VER',
  EXAM_INTERN_IELTS_EXPORTAR             = 'SERVICIO.EXAM_INTERN.IELTS_EXPORTAR',
  EXAM_INTERN_IELTS_APLICAR_CONFIRMACION = 'SERVICIO.EXAM_INTERN.IELTS_APLICAR_CONFIRMACION',
  EXAM_INTERN_B2F_VER                    = 'SERVICIO.EXAM_INTERN.B2F_VER',
  EXAM_INTERN_B2F_EXPORTAR               = 'SERVICIO.EXAM_INTERN.B2F_EXPORTAR',
  EXAM_INTERN_B2F_APLICAR_CONFIRMACION   = 'SERVICIO.EXAM_INTERN.B2F_APLICAR_CONFIRMACION',
  EXAM_INTERN_TOEFL_VER                  = 'SERVICIO.EXAM_INTERN.TOEFL_VER',
  EXAM_INTERN_TOEFL_EXPORTAR             = 'SERVICIO.EXAM_INTERN.TOEFL_EXPORTAR',
  EXAM_INTERN_TOEFL_APLICAR_CONFIRMACION = 'SERVICIO.EXAM_INTERN.TOEFL_APLICAR_CONFIRMACION',
}

/**
 * Permisos del módulo COMERCIAL (Menú Comercial)
 */
export enum ComercialPermission {
  // Contrato
  MODIFICAR_CONTRATO = 'COMERCIAL.CONTRATO.MODIFICAR',
  ENVIAR_PDF = 'COMERCIAL.CONTRATO.ENVIAR_PDF',
  DESCARGAR = 'COMERCIAL.CONTRATO.DESCARGAR',
  APROBACION_AUTONOMA = 'COMERCIAL.CONTRATO.APROBACION_AUTONOMA',

  // Prospectos
  VER_PROSPECTOS = 'COMERCIAL.PROSPECTOS.VER',
}

/**
 * Permisos del módulo MANTENIMIENTO (Menú Mantenimiento - SUPER_ADMIN)
 */
export enum MantenimientoPermission {
  // Contratos
  MIGRAR_CONTRATO   = 'MANTENIMIENTO.CONTRATOS.MIGRAR',
  BLOQUEAR_CONTRATO = 'MANTENIMIENTO.CONTRATOS.BLOQUEAR',
  // Usuarios
  CLEAR_HISTORIC    = 'MANTENIMIENTO.USUARIOS.CLEAR_HISTORIC',
  EDICION_CONTRATO  = 'MANTENIMIENTO.USUARIOS.EDICION_CONTRATO',
  ENVIO_MENSAJES    = 'MANTENIMIENTO.USUARIOS.ENVIO_MENSAJES',
  CREAR_ROL         = 'MANTENIMIENTO.USUARIOS.CREAR_ROL',
  GENERAR_CONTRATO  = 'MANTENIMIENTO.USUARIOS.GENERAR_CONTRATO',
  CONTRATOS_PRUEBA  = 'MANTENIMIENTO.USUARIOS.CONTRATOS_PRUEBA',
  // Avisos
  AVISOS_TICKER     = 'MANTENIMIENTO.AVISOS.TICKER',
  AVISOS_BANNER     = 'MANTENIMIENTO.AVISOS.BANNER',
  // Material
  ACTUALIZAR_VIDEOS = 'MANTENIMIENTO.MATERIAL.ACTUALIZAR_VIDEOS',
  // Plantillas
  PLANTILLAS_GESTION = 'MANTENIMIENTO.PLANTILLAS.GESTION',
  // Scripts
  SCRIPTS_USUARIOS_PEGADOS = 'MANTENIMIENTO.SCRIPTS.USUARIOS_PEGADOS',
  SCRIPTS_CONSULTA         = 'MANTENIMIENTO.SCRIPTS.CONSULTA',
}

/**
 * Permisos del módulo RECAUDOS (Menú Recaudos)
 */
export enum RecaudosPermission {
  GESTION_VER         = 'RECAUDOS.GESTION.VER',
  ASIGNACION_VER      = 'RECAUDOS.ASIGNACION.VER',
  ASIGNACION_EXPORTAR = 'RECAUDOS.ASIGNACION.EXPORTAR',
}

/**
 * Permisos del módulo APROBACION (Menú Aprobación)
 */
export enum AprobacionPermission {
  // Modificar (usado en Wix)
  ACTUALIZAR = 'APROBACION.MODIFICAR.ACTUALIZAR',
  EXPORTAR_CSV = 'APROBACION.MODIFICAR.EXPORTAR_CSV',
  VER_CONTRATO = 'APROBACION.MODIFICAR.CONTRATO',
  ENVIAR_PDF = 'APROBACION.MODIFICAR.ENVIAR_PDF',
  DESCARGAR = 'APROBACION.MODIFICAR.DESCARGAR',
  APROBACION_AUTONOMA = 'APROBACION.MODIFICAR.APROBACION_AUTONOMA',

  // Legacy (mantener compatibilidad)
  GLOBAL_ACTUALIZAR = 'APROBACION.GLOBAL.ACTUALIZAR',
  GLOBAL_EXPORTAR_CSV = 'APROBACION.GLOBAL.EXPORTAR_CSV',
}

// ============================================================================
// TIPO UNION DE TODOS LOS PERMISOS
// ============================================================================

/**
 * Tipo que representa cualquier permiso válido en el sistema
 */
export type Permission =
  | PersonPermission
  | StudentPermission
  | AcademicoPermission
  | ServicioPermission
  | ComercialPermission
  | AprobacionPermission
  | MantenimientoPermission
  | InformesPermission
  | RecaudosPermission;

// ============================================================================
// INTERFACES
// ============================================================================

/**
 * Definición de un permiso con sus metadatos
 */
export interface PermissionDefinition {
  code: Permission;
  module: Module;
  section: string;
  name: string;
  description: string;
}

/**
 * Matriz de permisos para un rol específico
 */
export interface RolePermissions {
  role: Role;
  permissions: Permission[];
}

/**
 * Usuario con rol y permisos
 */
export interface UserWithPermissions {
  id: string;
  email: string;
  name: string;
  role: Role;
  permissions: Permission[];
}

/**
 * Resultado de verificación de permisos
 */
export interface PermissionCheck {
  allowed: boolean;
  reason?: string;
}
